spring.application.name=sulwork-cafe
spring.datasource.url=jdbc:postgresql://localhost:5432/sulwork_cafe
spring.datasource.username=sulwork
spring.datasource.password=sulwork

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.sql.init.mode=always
